FACENET_WEIGHTS = "models/facenet/facenet_weights.h5"
EMBEDDINGS = 'embeddings/embeddings.pkl'
FACES_TRAINING_DIR = 'faces/training/'
FACES_TMP_DIR = 'faces/tmp/'
EXIT_VIDEO_KEY = 'q'
WINDOW_NAME = 'Video'
UNKNOWN = 'unknown'
CONFIDENCE = 0.99
RECOGNITION = 0.5
REQUIRED_SIZE = (160, 160)
